[package]
name = "lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "lox"
source = "main.rs"

[dependencies]
phf = { version = "0.11.2", features = ["macros"]}
thiserror = "1.0.52"
